import { StyleSheet } from "react-native";
import { v, wh, ww } from "../../../components/stylesVar";

export default StyleSheet.create({
  ctn: {
    padding: 20,
    display: "flex",
    gap: 14,
    paddingTop: wh * 0.15,
    minHeight: wh,
    // alignItems: "center",
  },
  btn_ctn: ({ pressed }) => ({
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    opacity: pressed ? 0.5 : 1,
    paddingHorizontal:0
  }),
  btn_login: {
    borderRadius: 100,
    height: 50,
    width: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: v.four,
  },
  tc: {
    color: v.four,
  },
  not_code: {
    marginTop: "auto",
    borderBottomWidth: 1,
    borderColor: v.four,
    alignSelf: "center",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logo_ctn: ({ pressed }) => ({
    height: 200,
    width: 200,
    alignSelf: "center",
    // backgroundColor: v.third,
    borderRadius: 12,
    opacity: pressed ? 0.5 : 1,
    borderWidth: 1,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  }),
  logo: {
    width: "100%",
    height: "100%",
  },
  logo_btn: ({ pressed }) => ({
    opacity: pressed ? 0.5 : 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: v.four,
    width: 36,
    height: 36,
    borderRadius: 6,
  }),
  logo_btn_a: ({ pressed }) => ({
    opacity: pressed ? 0.5 : 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: v.four,
    backgroundColor: v.four,
    width: 36,
    height: 36,
    borderRadius: 6,
  }),
  btn_landscape: {
    height: 15,
    width: 20,
    borderWidth: 2,
    borderColor: v.four,
  },
  btn_portrait: {
    height: 20,
    width: 15,
    borderWidth: 2,
    borderColor: v.four,
  },
  btn_square: {
    height: 20,
    width: 20,
    borderWidth: 2,
    borderColor: v.four,
  },
  subtitle_ctn: {
    display: "flex",
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    marginTop: 12,
  },
  scc_modal2: {
    // justifyContent: "center",
    width: ww,
    height: wh,
    backgroundColor: v.four,
    position: "absolute",
    display: "flex",
    padding: 20,
    paddingTop: 200,
    alignItems: "center",
    zIndex: 200,
  },
  sub_ctn2: {
    gap: 14,
  },
  btn_ctn2: ({ pressed }) => ({
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 50,
    opacity: pressed ? 0.5 : 1,
  }),
  btn_login2: {
    borderRadius: 100,
    height: 50,
    width: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: v.prime,
  },
  tc2: {
    color: v.prime,
  },
});
