export const isOffline = true
export const url = "idk yet"

export const items = [
    {
        _id:"001",
        name:'Item 1',
        price:45.00,
        description:'',
        categories:['home','clean'],
        owner_id:'0001',
        units_type:1,
        favorites:[],
        reviews:[],
        images:["a"],
    },
    {
        _id:"002",
        name:'Item 2',
        price:1.00,
        description:'',
        categories:['clean','cloth'],
        owner_id:'0001',
        units_type:1,
        favorites:[],
        reviews:[{stars:4},{stars:5},{stars:2},{stars:3}],
        images:["a"],
    },{
        _id:"003",
        name:'Item 3',
        price:29.99,
        description:'',
        categories:['cloth','food'],
        owner_id:'0001',
        units_type:1,
        favorites:[],
        reviews:[],
        images:["a"],
    },{
        _id:"004",
        name:'Item 4',
        price:5.99,
        description:'',
        categories:['tech','others'],
        owner_id:'0001',
        units_type:1,
        favorites:[],
        reviews:[],
        images:["a"],
    },{
        _id:"005",
        name:'Item 1',
        price:51.00,
        description:'',
        categories:['others','home'],
        owner_id:'0001',
        units_type:1,
        favorites:[],
        reviews:[],
        images:["a"],
    },{
        _id:"006",
        name:'Item 6',
        price:120.99,
        description:'',
        categories:['tech'],
        owner_id:'0001',
        units_type:1,
        favorites:[],
        reviews:[],
        images:["a"],
    }
]
